FROM python:3.12-slim

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Installer les dépendances Python communes
RUN pip install --no-cache-dir \
    pyspark==3.5.1 \
    kafka-python==2.0.2 \
    opencv-python==4.9.0.80 \
    ultralytics==8.3.0 \
    pandas==2.2.2 \
    docker-compose -f docker/docker-compose.yml up --build -d==1.34.0